target-version = "py310"

[lint]
select = [
    # https://docs.astral.sh/ruff/rules/#flake8-bugbear-b
    # https://github.com/PyCQA/flake8-bugbear
    "B",
    # https://docs.astral.sh/ruff/rules/#flake8-blind-except-ble
    # https://github.com/elijahandrews/flake8-blind-except
    "BLE",
    # https://docs.astral.sh/ruff/rules/#flake8-comprehensions-c4
    # https://github.com/adamchainz/flake8-comprehensions
    "C4",
    # https://docs.astral.sh/ruff/rules/#error-e
    # https://github.com/PyCQA/pycodestyle
    "E",
    # https://docs.astral.sh/ruff/rules/#pyflakes-f
    # https://github.com/PyCQA/pyflakes
    "F",
    # https://docs.astral.sh/ruff/rules/#isort-i
    # https://pycqa.github.io/isort/
    "I",
    # https://docs.astral.sh/ruff/rules/#flake8-use-pathlib-pth
    # https://gitlab.com/RoPP/flake8-use-pathlib
    "PTH",
    # https://docs.astral.sh/ruff/rules/#ruff-specific-rules-ruf
    # Project link is the astral/ruff website, so no external links.
    "RUF",
    # https://docs.astral.sh/ruff/rules/#flake8-simplify-sim
    # https://github.com/MartinThoma/flake8-simplify
    "SIM",
    # https://docs.astral.sh/ruff/rules/#flake8-tidy-imports-tid
    # https://github.com/adamchainz/flake8-tidy-imports
    "TID",
    # https://docs.astral.sh/ruff/rules/#pyupgrade-up
    # https://github.com/asottile/pyupgrade
    "UP",
    # https://docs.astral.sh/ruff/rules/#warning-w
    # https://github.com/PyCQA/pycodestyle
    "W",
]
extend-safe-fixes = [
    # https://docs.astral.sh/ruff/rules/non-pep585-annotation/
    "UP006",
]
isort.required-imports = [ "from __future__ import annotations" ]
